version: "3.9"

services:
  hello-service:
    build: ./hello-service
    ports:
      - "3000:3000"
    environment:
      - PORT=3000

  bye-service:
    build: ./bye-service
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
